version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api-prod
    ports:
      - "8000:8000"
    environment:
      # LLM Provider Configuration - ChatGroq only
      - LLM_PROVIDER=${LLM_PROVIDER:-chatgroq}
      
      # ChatGroq Configuration
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_BASE_URL=${GROQ_BASE_URL:-https://api.groq.com/openai/v1}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME:-llama3-8b-8192}
      
      # LLM Configuration
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - MAX_TOKENS=${MAX_TOKENS:-1024}
      
      # Memory Configuration
      - MEMORY_TTL_SECONDS=${MEMORY_TTL_SECONDS:-7200}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE:-2000}
      
      # Authentication Configuration
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://user:password@db:5432/chatbot}
    volumes:
      - chatbot_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - chatbot
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  chatbot_data:
    driver: local