version: '3.8'

services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    ports:
      - "8000:8000"
    environment:
      # LLM Provider Configuration - ChatGroq only
      - LLM_PROVIDER=${LLM_PROVIDER:-chatgroq}
      
      # ChatGroq Configuration
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_BASE_URL=${GROQ_BASE_URL:-https://api.groq.com/openai/v1}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME:-llama3-8b-8192}
      
      # LLM Configuration
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - MAX_TOKENS=${MAX_TOKENS:-1024}
      
      # Memory Configuration
      - MEMORY_TTL_SECONDS=${MEMORY_TTL_SECONDS:-3600}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE:-1000}
      
      # Authentication Configuration
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - chatbot_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  chatbot_data:
    driver: local