version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_BASE_URL=${GROQ_BASE_URL:-https://api.groq.com/openai/v1}
      - MODEL_NAME=${MODEL_NAME:-llama3-8b-8192}
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - MAX_TOKENS=${MAX_TOKENS:-1024}
      - MEMORY_TTL_SECONDS=${MEMORY_TTL_SECONDS:-3600}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE:-1000}
    volumes:
      - ./app:/app/app:ro  # Mount for development (read-only in container)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s