name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if different (e.g., 'master')

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other runners if needed (e.g., 'macos-latest')

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in secrets

      # Step 4: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .  # The path to your Dockerfile
          push: true  # Set this to true to push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/medbackend:latest  # Docker Hub repository name and tag
